# Generated by Django 4.0.4 on 2022-06-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('additionalinfo', models.CharField(max_length=150)),
                ('is_barrier_free', models.BooleanField()),
                ('has_computer', models.BooleanField()),
            ],
        ),
    ]
