# Generated by Django 4.0.5 on 2022-06-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_date_reservation_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration',
            field=models.IntegerField(default=None),
        ),
    ]
