# Generated by Django 4.0.5 on 2022-06-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='username',
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
