# Generated by Django 4.0.5 on 2022-06-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_reservation_username_reservation_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='seat_id',
            field=models.IntegerField(default=None),
        ),
    ]
