# Generated by Django 4.0.5 on 2022-07-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_reservation_is_rated_is_a_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_a_group',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='workspacename',
        ),
        migrations.AddField(
            model_name='reservation',
            name='group_id',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seat_id',
            field=models.CharField(max_length=50),
        ),
    ]
