# Generated by Django 4.0.5 on 2022-07-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='workspace_rating',
            field=models.FloatField(default=0),
        ),
    ]
