# Generated by Django 4.0.5 on 2022-07-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspace_workspace_rating_alter_workspace_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='group',
            field=models.CharField(max_length=25),
        ),
    ]
